# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('UserIcon', models.CharField(max_length=100)),
                ('UserDetail', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('UserTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('UserTypeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='UserTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctadmin.UserType'),
        ),
    ]
