# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserTypeID',
            field=models.IntegerField(default=0),
        ),
    ]
