# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctadmin', '0002_auto_20160519_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('HospitalID', models.AutoField(primary_key=True, serialize=False)),
                ('HospitalName', models.CharField(max_length=50)),
                ('HospitalCont', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('MedicineID', models.AutoField(primary_key=True, serialize=False)),
                ('MedicineName', models.CharField(max_length=50)),
                ('MedicineCont', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pathema',
            fields=[
                ('PathemaID', models.AutoField(primary_key=True, serialize=False)),
                ('PathemaName', models.CharField(max_length=50)),
                ('PathemaTypeID', models.IntegerField(default=0)),
                ('PathemaCont', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PathemaType',
            fields=[
                ('PathemaTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('PathemaTypeName', models.CharField(max_length=50)),
                ('PathemaTypeDetail', models.IntegerField(default=1)),
                ('SuperType', models.IntegerField(default=0)),
            ],
        ),
    ]
