# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctadmin', '0003_hospital_medicine_pathema_pathematype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='HospitalCont',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='MedicineCont',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pathema',
            name='PathemaCont',
            field=models.TextField(),
        ),
    ]
