# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctadmin', '0004_auto_20160519_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ArticleID', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleTitile', models.CharField(max_length=30)),
                ('ArticleDesc', models.TextField()),
                ('ArticlePic', models.CharField(max_length=100)),
                ('PathemaTypeID', models.IntegerField(default=0)),
                ('UserID', models.IntegerField(default=0)),
                ('CreateTime', models.DateField(auto_now_add=True)),
                ('Like', models.IntegerField(default=0)),
                ('Comm', models.IntegerField(default=0)),
                ('Send', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('CommunityID', models.AutoField(primary_key=True, serialize=False)),
                ('CommunityTitle', models.CharField(max_length=30)),
                ('CommunityDesc', models.TextField()),
                ('CommunityPic', models.CharField(max_length=100)),
                ('PathemaTypeID', models.IntegerField(default=0)),
                ('UserID', models.IntegerField(default=0)),
                ('CreateTime', models.DateField(auto_now_add=True)),
                ('Like', models.IntegerField(default=0)),
                ('Comm', models.IntegerField(default=0)),
                ('Send', models.IntegerField(default=0)),
            ],
        ),
    ]
