# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctadmin', '0005_article_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleID', models.IntegerField(default=0)),
                ('CommunityID', models.IntegerField(default=0)),
                ('UserID', models.IntegerField(default=0)),
                ('Content', models.CharField(max_length=255)),
                ('CreateTime', models.DateField(auto_now_add=True)),
                ('Read', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('FavouriteID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField(default=0)),
                ('ArticleID', models.IntegerField(default=0)),
                ('CommunityID', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('SubscribeID', models.AutoField(primary_key=True, serialize=False)),
                ('UserID', models.IntegerField(default=0)),
                ('PathemaTypeID', models.IntegerField(default=0)),
                ('sub', models.IntegerField(default=0)),
            ],
        ),
    ]
