# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctadmin', '0007_auto_20160519_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ArticlePic',
            field=models.FileField(upload_to='./media/upload/article'),
        ),
        migrations.AlterField(
            model_name='community',
            name='CommunityPic',
            field=models.FileField(upload_to='./media/upload/community'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserIcon',
            field=models.FileField(upload_to='./media/upload/icon'),
        ),
    ]
